
easy_admin:
    design:
        assets:
            css:
                - 'bundles/app/easy_admin_custom.css'

    entities:
        User:
            class: AppBundle\Entity\User
            controller: AppBundle\Admin\FosUserAdminController

            form:
                fields:
                    - username
                    - email
                    - enabled
                    - lastLogin
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }

            edit:
                fields:
                    - { property: 'plainPassword', type_options: { required: false} }
                form_options: { validation_groups: ['Profile'] }
            new:
                fields:
                    - { property: 'plainPassword', type_options: { required: true} }
                form_options: { validation_groups: ['Registration'] }

            list:
                actions: [ 'show' ]


        Link:
            class: AppBundle\Entity\Link
            form:
                fields:
                    - url
                    - status
                    - checkedAt
                    - statusCode
                    - { property: 'status', type: 'choice', type_options: { choices: { 'Parsed': 'parsed', 'Waiting': 'waiting', 'Skipped': 'skipped' }, allow_extra_fields: false } }


            list:
#                max_results: 2000
                actions: [ 'show' ]
                fields:
                    - url
                    - status
                    - checkedAt
                    - statusCode
                    - { property: 'validation', template: 'field_array.html.twig' }
                    - { property: 'rawUrls', template: 'raw_urls.html.twig' }
            show:
                fields:
                    - checkedAt
                    - { property: 'url'}
                    - { property: 'status'}
                    - { property: 'statusCode'}
                    - { property: 'statusMessage'}
                    - { property: 'parent'}
                    - { property: 'metas'}
                    - { property: 'responseHeaders'}
                    - { property: 'robots', template: 'html_content.html.twig' }
                    - { property: 'response', template: 'html_content.html.twig' }
                    - { property: 'rawUrls', template: 'raw_urls.html.twig' }
                    - { property: 'children', template: 'children_links.html.twig' }
                    - { property: 'validation'}
