version: "3.1"
services:
    db:
      image: mariadb:10.1
      working_dir: /application
      volumes:
        - ./volume/db/data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    webserver:
      image: nginx:alpine
      working_dir: /application
      volumes:
          - ${SYMFONY_APP_PATH}:/application
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./volume/logs/nginx:/var/log/nginx
      ports:
          - "80:80"

    php:
      build: php-fpm
      working_dir: /application
      volumes:
          - ${SYMFONY_APP_PATH}:/application
          - ./php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf # config php-fpm
          - ./php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini #config php
          - ./volume/logs/symfony:/application/var/logs
